movieForum/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :movies
  
  get '/movie/search' , to: 'movies#search'
  post '/movie/search' ,  to: 'movies#create'
  get '/movie/show' , to: 'movies#show'
  get '/posts/new/:id', to: 'posts#new', as: :movie_posts
  post '/posts/new/:id', to: 'posts#create', as: :posts_new
  post '/movie/create' , to: 'movies#create', as: :create_movie
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

movieForum/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

movieForum/app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :posts
end

movieForum/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :movie
end

movieForum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

movieForum/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def search
    @q = params[:q]
    #@movie = Movie.all
   
    if @q
      @movies=[]
      @movies << Movie.find_by(tittle: params[:q])
      unless @movies.present?
        @movies=[]
        json = JSON.parse(open("http://www.omdbapi.com/?s=#{@q}&Pages=20").read, symbolize_keys: true)
        json['Search'].each do  |movie|
          #puts movie['Title']
          tempMovie=Movie.new
          tempMovie.tittle=movie['Title']
          tempMovie.poster=movie['Poster']
          tempMovie.year=movie['Year']
          #@tempMovie.sypnosis=movie['Plot']
          @movies<<tempMovie
          puts tempMovie.tittle
        end 
      end
    end
  end

  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    #respond_to do |format|
      if @movie.save
        redirect_to "/posts/new/#{@movie.id}"
        #format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        #format.json { render :show, status: :created, location: @movie }
      else
        #format.html { render :new }
        #format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      puts params
      params.permit(:tittle, :poster, :year, :synopsis)
    end
end

movieForum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    
    @movie = Movie.find_by(id: params[:id])
    @post = @movie.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)

    @movie = Movie.find_by(id: params[:id])
    @post = @movie.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user, :comment)
    end
end

movieForum/app/helpers/application_helper.rb
module ApplicationHelper
end

movieForum/app/helpers/movies_helper.rb
module MoviesHelper
end

movieForum/app/helpers/posts_helper.rb
module PostsHelper
end

movieForum/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

movieForum/app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>

  <div class="field">
    <%= f.label :poster %>
    <%= f.text_field :poster %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_field :synopsis %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movieForum/app/views/movies/_search.html.erb
<%if !@movies%>
<h1>New search</h1>
<form>
 <input name=q <%= @q %> >
 <button type=”submit”>Buscar</button>
</form>
<%else%>
    <div id="error_explanation">
      <h2>Results to <%=@q%></h2>
      <ul>
      <% @movies.each do |movie| %>
        <li><%= movie.tittle %></li>
        <img src="<%=movie.poster%>" style="max-width:50%;">
        <%if !movie.id%>
        <%= link_to 'Start a discussion', create_movie_path(:tittle => "#{movie.tittle}", :poster =>"#{movie.poster}", :year =>"#{movie.year}"), method: :post %>
        <%else%>
        <%= link_to 'discussion', "/posts/new/#{movie.id}", method: :get %>
        <% movie.posts.each do |post|%>
          <h6><%=post.user%>.<h3><%=post.comment%>
        <%end%>
        <%end%>
      <% end %>
      </ul>
    </div>
<%end%>

movieForum/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

movieForum/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Poster</th>
      <th>Year</th>
      <th>Synopsis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.tittle %></td>
        <td><%= movie.poster %></td>
        <td><%= movie.year %></td>
        <td><%= movie.synopsis %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

movieForum/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

movieForum/app/views/movies/search.html.erb
<%= render 'search', search: @search%>

<%= link_to 'Back', movies_path %>

movieForum/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @movie.tittle %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @movie.poster %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

movieForum/app/views/posts/_form.html.erb
<%= form_for [@movie, @post] do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2><%=@movie.tittle%></h2>
  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movieForum/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

movieForum/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user %></td>
        <td><%= post.comment %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

movieForum/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

movieForum/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>